version: '3.2'

services:
  # MariaDB container
  db_m2:
    image: mariadb:10.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento2_db

  # RabbitMQ container
  rabbitmq_m2:
    image: rabbitmq:3.7
    hostname: magento2.dev.nos.to # Your Magento 2 installation host
    container_name: rabbitmq_m2
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"
  
  # Magento 2 container
  magento2:
    build:
      context: ./.docker
      dockerfile: ./Dockerfile
    links:
      - db_m2
      - rabbitmq_m2
    ports:
      - 80:80
    extra_hosts:
      my.dev.nos.to: 192.168.65.2

    volumes:
      - type: bind
        source: .
        target: /var/www/html/magento2/app/code/Nosto/Tagging
      - type: bind
        source: ./log
        target: /var/www/html/magento2/var/log/
      - type: bind
        source: ./vendor/magento
        target: /var/www/html/magento2/generated
    environment:
      PHP_DEBUGGER: null
      COMPOSER_AUTH: "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"\",\"password\":\"\"}}}"
      MYSQL_HOST: db_m2
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: magento2_db
      RABBITMQ_HOST: rabbitmq_m2
      VIRTUAL_HOST: magento2.dev.nos.to
      ADMIN_USER: admin
      ADMIN_PASSWORD: Admin12345
      # CONNECT_NOSTO: null
      # NOSTO_ACCOUNT_ID:
      # SSO_TOKEN:
      # PRODUCTS_TOKEN:
      # SETTINGS_TOKEN:
      # RATES_TOKEN:
      # APPS_TOKEN:
      # EMAIL_TOKEN:
      # STORE_VIEW_SCOPE_CODE:
      # Use the env vars bellow to point to your local or staging play instance
      NOSTO_SERVER_URL: connect.my.dev.nos.to
      NOSTO_API_BASE_URL: http://host.docker.internal:9000/api
      NOSTO_OAUTH_BASE_URL: https://my.dev.nos.to/oauth
      NOSTO_WEB_HOOK_BASE_URL: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN_REGEXP: .*

