version: '3.2'

services:
  # MariaDB container
  db_m2:
    build:
      context: ./.docker/mariadb
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento2_db
    volumes:
      - .docker/mysql_data:/var/lib/mysql:delegated

  # RabbitMQ container
  rabbitmq_m2:
    image: rabbitmq:3.7-management
    hostname: magento2.dev.nos.to # Your Magento 2 installation host
    container_name: rabbitmq_m2
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672" # For management

  # Elastic Search container
  es_m2:
    image: elasticsearch:6.8.4
    environment:
      discovery.type: single-node

  # Magento 2 container
  magento2:
    build:
      context: ./.docker
      dockerfile: ./Dockerfile
    links:
      - db_m2
      - rabbitmq_m2
      - es_m2
    ports:
      - 8081:80
      - 9002:9002 #XDebug
    extra_hosts:
      my.dev.nos.to: 192.168.65.2
    volumes:
      - type: bind
        source: .
        target: /var/www/html/magento2/app/code/Nosto/Tagging
      - type: bind
        source: ./log
        target: /var/www/html/magento2/var/log/
      - type: bind
        source: ./vendor/magento
        target: /var/www/html/magento2/generated
    environment:
      COMPOSER_AUTH: "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"\",\"password\":\"\"}}}"
      MYSQL_HOST: db_m2
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: magento2_db
      RABBITMQ_HOST: rabbitmq_m2
      VIRTUAL_HOST: magento2.dev.nos.to:8081
      ES_HOST: es_m2
      ADMIN_USER: admin
      ADMIN_PASSWORD: Admin12345
      # Use the env vars bellow to point to your local or staging play instance
      NOSTO_SERVER_URL: connect.my.dev.nos.to
      NOSTO_API_BASE_URL: http://host.docker.internal:9000/api
      NOSTO_OAUTH_BASE_URL: https://my.dev.nos.to/oauth
      NOSTO_WEB_HOOK_BASE_URL: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN_REGEXP: .*
      XDEBUG_CONFIG: remote_host=host.docker.internal
